chore: update of common workflows

diff --git a/.github/workflows/profanity-filter.yaml b/.github/workflows/profanity-filter.yaml
--- a/.github/workflows/profanity-filter.yaml
+++ b/.github/workflows/profanity-filter.yaml
@@ -15,4 +15,13 @@ permissions:
 
 jobs:
   call-apply-filter:
+    if: ${{ github.event_name == 'issue_comment' || github.event_name == 'issues' || (github.event_name == 'pull_request' && github.event.pull_request.base.repo.id == github.event.pull_request.head.repo.id) }}
     uses: Netcracker/qubership-workflow-hub/.github/workflows/profanityFilter.yaml@main
+  warning:
+    runs-on: ubuntu-latest
+    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.repo.id != github.event.pull_request.head.repo.id }}
+    steps:
+      - name: "Warning"
+        run: |
+          echo "⚠️ Pull request from fork! ⚠️" >> $GITHUB_STEP_SUMMARY
+          echo "The action cannot be run over PRs from fork." >> $GITHUB_STEP_SUMMARY
